name: Trigger auto deployment for expresssample968a9d9ea03f

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/expresssample968a9d9ea03f-AutoDeployTrigger-ffd1f31f-f343-4872-afb3-8fdb2a20e575.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EXPRESSSAMPLE968A9D9EA03F_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EXPRESSSAMPLE968A9D9EA03F_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EXPRESSSAMPLE968A9D9EA03F_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.EXPRESSSAMPLE968A9D9EA03F_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EXPRESSSAMPLE968A9D9EA03F_REGISTRY_PASSWORD }}
          containerAppName: expresssample968a9d9ea03f
          resourceGroup: expresssample968a9d9e
          imageToBuild: default/expresssample968a9d9ea03f:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


